### PR TITLE
Fixes #135 by replacing mockito internal functions

### LINKED ISSUE #135: Runtime error using Mockito 4.5.0
**Describe the bug**
When using Mockito 4.5.0 you will see the following error (Maven output):

```
[ERROR] Errors: 
[ERROR]   SettingsStoreTest.closes » UnfinishedMockingSession 
Unfinished mocking session detected.
Previous MockitoSession was not concluded with 'finishMocking()'.
For examples of correct usage see javadoc for MockitoSession class.
[ERROR]   SettingsStoreTest.emptySettings » NoClassDefFound org/mockito/internal/util/reflection/Fields
[ERROR]   SettingsStoreTest.getSettings » UnfinishedMockingSession 
```

**To Reproduce**
Set the mockito dependency to 4.5.0 (https://github.com/mockito/mockito/releases/tag/v4.5.0)

**Expected behavior**
Tests should tun without an error

### PR DESCRIPTION
**Pull request by reinhapa**
Replaced usage of Mockito internal classes by custom function implementing same behaviour.

This should allow to get the PR #136 to be working.

### CODE REVIEW

File: src/main/java/org/simplify4u/slf4jmock/mockito/LoggerAnnotationEngine.java [hunk 1]
```diff
@@ -66,9 +67,21 @@ public AutoCloseable process(Class<?> clazz, Object testInstance) {
         };
     }
 
+    private static List<InstanceField> allDeclaredFieldsOf(Object testInstance) {
+        List<InstanceField> result = new ArrayList<>();
+        for (Class<?> clazz = testInstance.getClass();
+             clazz != Object.class;
+             clazz = clazz.getSuperclass()) {
```
Comment (slawekjaranowski) [inline src/main/java/org/simplify4u/slf4jmock/mockito/LoggerAnnotationEngine.java:74]: Pleas try to put in one line ... multiple line for `for` statement can be mislead 😄 
if line will be too long, we can try rename variable `testInstance` to something shorter

**Comment by slawekjaranowski** [comment]
thanks a lot

**Review by slawekjaranowski — APPROVED** [review]
